config/routes.rb
CodeMountain::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users
  resources :users, :only => [:show]

  root :to => 'pages#landing'
  controller :pages do
    get 'about'
    get 'congrats'
    get 'contact'
    post 'create_subscriber'
    get 'dashboard'
    get 'fake_iframe'
    get 'faq'
    get 'get_help'
    get 'get_response'
    get 'help'
    get 'help_confirm'
    get 'mobile'
    get 'start'
    get 'thank_you'
    get 'tutorial'
  end

  match 'real_dashboard' => 'dashboard#index'

  resources :tasks, :only => [:create, :show, :update] do
    member do
      get :tutorial
      get :complete
      get :help
    end
  end

  resources :lessons, :only => [:index]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :tasks

  def self.incomplete(user)
    # FIXME: This will query every lesson and it's task, but NOT IN doesn't work
    Lesson.all.reject do |l|
      l.task(user) && l.task(user).complete?
    end
  end

  def task(user)
    tasks.where(:user_id => user.id).first
  end

  def next
    Lesson.find(id + 1)
  end
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  validates_presence_of :name
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :allow_blank => false

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :lesson
  belongs_to :user

  validates_presence_of :lesson_id
  validates_presence_of :user_id

  delegate :title, :to => :lesson
  delegate :detail, :to => :lesson
  delegate :link, :to => :lesson
  delegate :benefits, :to => :lesson

  def complete?
    status == 'complete'
  end

  def next
    user.start(lesson.next)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  has_many :tasks

  validates_presence_of :name
  validates_uniqueness_of :email, :case_sensitive => false

  def next_task
    start(Lesson.incomplete(self).first)
  end

  def start(lesson)
    find_task(lesson) || tasks.build(:lesson => lesson)
  end

  private
  def find_task(lesson)
    tasks.where(:lesson_id => lesson.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  expose(:next_task) {current_user.next_task}

  def index
    next_task.save!
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  expose(:lessons) {Lesson.all}

  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'marketing'

  def dashboard
    render :layout => 'application'
  end

  def start
    render :layout => 'application'
  end

  def congrats
    render :layout => 'application'
  end

  def tutorial
    render :layout => 'navless'
  end

  def fake_iframe
    render :layout => 'dialog'
  end

  def get_help
    render :layout => 'dialog'
  end

  def help_confirm
    render :layout => 'dialog'
  end

  def get_response
    render :layout => 'dialog'
  end
  
  def landing
    @subscriber = Subscriber.new
  end
  
  def create_subscriber
    @subscriber = Subscriber.new(params[:subscriber])
    if @subscriber.save 
      redirect_to thank_you_url 
    else
      render :landing 
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :update]

  expose(:task)
  expose(:next_task) {task.next}

  def create
    task.user = current_user
    task.save!
    redirect_to task_path(task)
  end

  def show
  end

  def update
    task.save!
    if params[:task][:status] == 'complete'
      next_task.save! #ensure it exists so page can navigate to it
      redirect_to complete_task_path(task)
    else
      redirect_to task_path(task)
    end
  end

  def tutorial
    render :layout => 'navless'
  end

  def help
    render :layout => 'dialog'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:user)

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_text(s)
    bc = BlueCloth.new(s)
    bc.to_html.html_safe
  end

  def help_link(task)
    link_to "I'm Stuck", help_task_path(task), :class => 'help'
  end
end

app/views/dashboard/index.html.haml
.wedge
  .right.column
    #next
      %h2 Continue Learning
      = link_to next_task.title, task_path(next_task)
    = image_tag('/images/Proficiency.png', :id => 'proficiency')
  .left.column
    = image_tag('/images/ProgressMountain.png', :id => 'mountain')

app/views/layouts/_bp_head.html.erb
<%= javascript_include_tag 'jquery.min' %>
<%= javascript_include_tag 'jquery.colorbox-min' %>
<%= javascript_include_tag :defaults %>

<%= stylesheet_link_tag 'style' %>
<%= stylesheet_link_tag 'colorbox' %>
<%= stylesheet_link_tag 'screen', :media => 'screen, projection'%>

<%= csrf_meta_tag %>

app/views/layouts/_crazyegg.html.haml
%script
   setTimeout(function(){var a=document.createElement("script");
   var b=document.getElementsByTagName('script')[0];
   a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0011/7165.js";
   a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1));

app/views/layouts/_debug.html.haml
- if false #Rails.env.development?
  .debug
    = debug(params)
    = debug(session)

app/views/layouts/_head.html.haml
= stylesheet_link_tag :all
= stylesheet_link_tag 'style'
= stylesheet_link_tag 'header'
= stylesheet_link_tag 'colorbox'
= favicon_link_tag '/images/favicon.png'
= javascript_include_tag :defaults
= javascript_include_tag 'jquery.colorbox-min'
= javascript_include_tag 'jquery.message_pop'

= csrf_meta_tag
= render('layouts/google_analytics') if Rails.env.production?

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Code Mountain
    = render 'layouts/head'
    = stylesheet_link_tag 'application'
%body{:class => "application #{controller_name} #{action_name}"}
  #main-header
    .container
      #logo
        = link_to image_tag( '/images/cm-logo-full.png'), root_path
    %nav
      - if user_signed_in?
        = gravatar_image_tag(current_user.email, :class => "profile-pic")
    
      %ul.header_links
        %li= render 'devise/menu/registration_items'
        %li= link_to "Dashboard", root_path
        %li= link_to "Messages", root_path
        %li= render 'devise/menu/login_items'
  .content
    %p.notice
      = notice
    %p.alert
      = alert
    = yield
  = render 'layouts/debug'
  = render 'layouts/crazyegg'

app/views/layouts/dialog.html.haml
!!! 5
%html
  %head
    %title Code Mountain
    = stylesheet_link_tag :all
    = stylesheet_link_tag 'tutorial'
    = javascript_include_tag 'application'
%body
  %div{:class => "dialog #{controller_name} #{action_name}"}
    = yield

app/views/layouts/marketing.html.haml
!!! 5
%html
  %head
    %title Code Mountain
    = render 'layouts/head'
    = stylesheet_link_tag 'marketing'
%body{:class => "marketing #{controller_name} #{action_name}"}
  #main-header
    .container
      #logo
        = link_to image_tag( '/images/cm-logo-full.png'), root_path
    %nav
      %ul.header_links
        %li= link_to "Home", root_path
        %li= link_to "About", about_path
  .content
    = yield
  = render 'layouts/debug'
  = render 'layouts/crazyegg'

app/views/layouts/navless.html.haml
!!! 5
%html
  %head
    %title Code Mountain
    = render 'layouts/head'
    = stylesheet_link_tag 'tutorial'
%body{:class => "application #{controller_name} #{action_name}"}
  = yield
  -# render 'layouts/debug'
  = render 'layouts/crazyegg'

app/views/lessons/_lesson.html.haml
%li
  = form_for current_user.start(lesson) do |f|
    = f.hidden_field :lesson_id
    = f.submit f.object.title
    = f.object.status

app/views/lessons/index.html.haml
%ul
  = render lessons

app/views/pages/about.html.haml
.container
  %img{:alt => "Code Mountain is an online journey that teaches beginners how to code in Ruby on Rails.", :src => "images/about1227.png"}/

app/views/pages/congrats.html.haml
.container
  .cl-30
  %img{:alt => "Congratulations! You have finished Task 3!", :src => "images/congrats_screen_03.png"}/
  

app/views/pages/contact.html.haml
.container.contact
  = link_to "Neal Sales-Griffin", "mailto:nealsalesgriffin@gmail.com"

app/views/pages/dashboard.html.haml
.container
  #fake_dashboard
    %img{:alt => "Your Dashboard", :src => "images/dashboard-main_03.png"}
    %a{:href => tutorial_path}
      %img#task_1{:alt => "Your Dashboard", :src => "images/continue_tutorial.jpg"}
    %img#avatar{:src => 'images/neal_03.png'}

app/views/pages/fake_iframe.html.haml
.content
  %img{:alt => "Welcome to Code Mountain", :src => "images/rails_for_zombies_02.jpg"}/

app/views/pages/faq.html.haml
.container
  %img{:alt => "FAQ", :src => "images/faq_images_03.png"}/
  %h2 
  What is Code Mountain exactly?  
  %p Code Mountain is a game that teaches beginners how to code in Ruby on Rails. 
  %h2 
  Why should I sign up for Code Mountain?
  %p Because you want learning how to code to be fun. You don’t want to have to go through all the pain of learning how to code. 
  %h2 Why do I want to learn how to code in the first place?
  %p You want to build your own solutions to problems. 
  %h2 
  What is Ruby on Rails?
  %p A popular web application programming language and framework.
  %h2 
  Why Ruby on Rails?
  %p It is accessible and easier for beginners to pick up. 
  %h2 
  How does Code Mountain work?
  %p You sign up, follow a list of pre-set tasks, track your progress, and use resources along the way. You are also plugged into a community of people who are willing to help you. 

  %h2 
    How much does Code Mountain cost?

  %p It’s free for the first 2 levels are free. Then it costs $____.  (includes awesome mobile app - link here). 

  %h2 
    Can I quit whenever I want if I don’t like it?

  %p Absolutely. Though, we will say that we think you’ll like Code Mountain so much, you won’t really want to ever leave. 

  %h2 
    What if I get stuck?

  %p We’ve built in functionality so you can get personalized help on specific challenges you run into along the way.

  %h2 
    Who is Code Mountain for?

  %p People who don’t consider themselves software developers. 

  %h2 
    Why was Code Mountain created?

  %p We tried to learn how to code and it was really hard. We believed there was a better way, and so created it.

app/views/pages/get_help.html.haml
#get_help
  = form_tag '/help_confirm', :class => 'help' do
    .help_title Help, I'm Stuck
    .help_detail
      .question
        Where did you get stuck?
      = text_area :help, :question, :rows => 5, :cols => 50, :value => "I'm stuck on Task 3: Rails for Zombies.\n\nZombie.find(3).graveyard = 'Benny Hills Memorial'\n"
      .send_to
        Send this to:
        .group
          = check_box 'help', 'friends',  :checked => 'checked'
          Your Friends
        .group
          = check_box 'help', 'experts'
          Expert Climbers
      .submit
        = image_submit_tag '/images/get_help_button.png'

app/views/pages/get_response.html.haml
#help_response
  .response_title
    .img
      = image_tag('/images/ri_avatar.png')
    .user_name
      Ri says...
  .response
    Hi Neal,
    %br
    You'll have to assign the zombie to a variable so you can save it afterwards.
    %br
    %br
    z = Zombie.find(3)
    %br
    z.graveyard = 'Benny Hills Memorial'
    %br
    z.save
    %br
    %br
    &mdash; Ri
  

app/views/pages/help_confirm.html.haml
#call_for_help
  .msg Your call for help has been sent!
  .batman
    = image_tag('/images/cmss.png')

app/views/pages/landing.html.haml
#splash.container
  %img{:alt => "Welcome to Code Mountain", :src => "images/landing_page_3.png"}/
  =form_for @subscriber, :url => { :action => "create_subscriber" }, :html => {:class => 'landing-form'} do |f|
    %h2 Are you ready to Climb?
    = f.label :name
    = f.text_field :name
    = f.label :email
    = f.text_field :email
    = f.submit ""
    - if @subscriber.errors.any?
      .errors
        Whoops! Some problems:
        %ul
        - @subscriber.errors.full_messages.each do |msg| 
          %li.error_msg
            =msg
      

app/views/pages/mobile.html.haml
.container
  %img{:alt => "iOS Phone Demo", :src => "images/IOSAPP.png"}/

app/views/pages/task.html.haml
%h2 Do This Task
%div
  %h3 Rails For Zombies
%div
  %h3 What You Learn
  %ul
    %li database modeling
    %li basic HTML

%div
  =link_to 'Complete', complete_path
  =link_to "I Can't Do This", help_path

app/views/pages/thank_you.html.haml
#thank_you.container
  %h2
    Thank you for your participation. Please help us improve the site by following the link below and filling out a
    %a{:href => "http://surveys.questionpro.com/akira/TakeSurvey?id=2483847"}
      short survey.
  
    
  
  

app/views/pages/tutorial.html.haml
#tutorial-header
  #main-header
    #logo_2
      = link_to image_tag( '/images/cm-logo-full.png'), root_path
    %nav
      %ul.header_links_2
        = link_to image_tag('leftbracket_red.png'), dashboard_path
        = link_to image_tag('imstuck.png'), get_help_path, :class => 'help'
        = link_to image_tag('finish_task.png'), congrats_path
#help_response_message
  .help_action
    .img
      = image_tag('/images/ri_avatar.png')
    .msg
      Ri has responded to your message.
      = link_to "Click Here to view.", get_response_path, :class => 'response'
#tutorialbody
  %iframe{:src => fake_iframe_path}

app/views/tasks/complete.html.haml
.congratulations
  %h3 Congratulations!
  %h2 You have finished #{task.title}!
.box
  %h3 You have now learned:
  .benefits
    = formatted_text(task.benefits)
  =link_to 'Dashboard', dashboard_path
  =link_to 'Proceed', task_path(next_task)

app/views/tasks/help.html.haml
= form_tag '/confirm_help', :class => 'help' do
  %h2 Help, I'm Stuck
  %p Where did you get stuck?
  = text_area :help, :question, :rows => 5
  %div
    %p Send this to:
    %p
      = check_box 'help', 'friends',  :checked => 'checked'
      Your Friends
    %p
      = check_box 'help', 'experts'
      Expert Climbers
  = submit_tag "Get Help"

app/views/tasks/show.html.haml
.container
  %h2.title #{task.title}
  %div
    .detail
      = formatted_text(task.detail)
    %p.link
      = link_to task.link, tutorial_task_path(task)

app/views/tasks/tutorial.html.haml
#tutorialheader
  #main-header
    .container
      #logo
        = link_to image_tag( '/images/cm-logo-full.png'), root_path
    
    %nav
      %ul.header_links
        %li
          = form_for task do |f|
            = f.hidden_field :status, :value => 'complete'
            = f.submit "Finish"
        %li
          = help_link(task)
#tutorialbody
  %iframe{:src => task.link}

app/views/users/show.html.haml
= user.name